@baseUrl = http://localhost:3333

@authToken = {{auth.response.body.accessToken}}

# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "User Test",
    "email": "usertest@test.com",
    "password": "paocomovo"
}

###

# @name auth
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "user1@test.com",
    "password": "paocomovo"
}

###

# @name createQuestion
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta4",
    "content": "Novo conteudo4"
}

###

# @name fetchRecentQuestions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}