@baseUrl = http://localhost:3333

@authToken = {{auth.response.body.accessToken}}

# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "User Test",
    "email": "usertest@test.com",
    "password": "paocomovo"
}

###

# @name auth
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "usertest@test.com",
    "password": "paocomovo"
}

###

# @name createQuestion
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova nova 2",
    "content": "Conteudo novo 2"
}

###

# @name fetchRecentQuestions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name editQuestion
PUT {{baseUrl}}/questions/df2e38a0-51f9-480a-bc48-19691b838591
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "New title",
    "content": "New content"
}