version: '3.8'

services:
  postgres:
    container_name: nestjs-clean-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nestjs-clean

  cache:
    container_name: nestjs-clean-cache
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - ./data/redis:/data
